### ISSUE TITLE
"Unexpected error while saving persistence" - on exit

### ISSUE THREAD

**Issue by Superbrka** [LogExperts/LogExpert#140]
Hello,

I get this error message on exit.
"Unexpected error while saving persistence: Object reference not set to an instance of an object."

- LogExpert Version: 1.8.2
- Windows Version: Windows 10
- Lokal file or Network: Local file
- Used Columnizer: Default (single line)
- Is this version specific or a new problem: Since 1.8.2 Version

![image](https://user-images.githubusercontent.com/49299443/67363037-c3195080-f56c-11e9-9665-c06e8c975e81.png)

[1.lxj.txt](https://github.com/zarunbal/LogExpert/files/3760501/1.lxj.txt)

**Comment by zarunbal** [comment]
Could you please upload the log file which contains the shown error ([see](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging))

**Comment by Superbrka** [comment]
Hello,

I've investigated this issue a bit, and found out it only comes when I try to monitor log file from the network, which is not accessible for some (permissions) reason, and then try to close it.

![2019-10-25 08_22_59-LogExpert - __deessconv07_c$_ConvertX_ConvertX_LOGS_ConvertX_25 10 2019 log](https://user-images.githubusercontent.com/49299443/67548411-11ac2380-f702-11e9-8386-7eeada6bb203.png)

**Comment by zarunbal** [comment]
> I've investigated this issue a bit, and found out it only comes when I try to monitor log file from the network, which is not accessible for some (permissions) reason, and then try to close it.

Did you set in the Persistence Settings to save "Same directory as log file"? That could explain the error. 

It would be great if you could share the log entry with the error from the log file

**Comment by Superbrka** [comment]
Hello,

I hope this helps

Bye



============================================================================
LogExpert 1.8.2 started.
============================================================================
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 0, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 1, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 2, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 3, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 4, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 5, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 25, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 100, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 200, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.8434|ERROR|LogExpert.LogfileReader|Cannot find buffer for line 400, file: C:\Users\masked_user_name\Desktop\9849775\Status.log
2019-10-30 13:37:12.9800|ERROR|LogExpert.LogWindow|Error loading bookmarks: Could not find file 'C:\Users\masked_user_name\Documents\LogExpert\C__Users_masked_user_name_Desktop_9849775_Status.log.lxp'. System.IO.FileNotFoundException System.IO.FileNotFoundException: Could not find file 'C:\Users\masked_user_name\Documents\LogExpert\C__Users_masked_user_name_Desktop_9849775_Status.log.lxp'.
File name: 'C:\Users\masked_user_name\Documents\LogExpert\C__Users_masked_user_name_Desktop_9849775_Status.log.lxp'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at LogExpert.Persister.Load(String fileName)
   at LogExpert.LogWindow.LoadPersistenceData()
![2019-11-04 12_56_41-Settings](https://user-images.githubusercontent.com/49299443/68119469-142d2b00-ff03-11e9-96df-698954feac51.png)

**Comment by Hirogen** [comment]
This seems to be in the same place as the portableMode Bug, I'll have a look tonight, and see what I can find out.

**Comment by fwilh** [comment]
_In a similar vein:_ I started getting  the error message `Unexpected error while saving persistence: Access to the path is denied.` when my organization enforced Windows Defender ATP’s ransomware protection, Controlled Folder Access (CFA).  LogExpert was not allowed to write to MyDocuments/LogExpert 

I worked around it by creating an `Own directory` for persistence file location under `AppData\Local`

**Comment by Hirogen** [comment]
> _In a similar vein:_ I started getting the error message `Unexpected error while saving persistence: Access to the path is denied.` when my organization enforced Windows Defender ATP’s ransomware protection, Controlled Folder Access (CFA). LogExpert was not allowed to write to MyDocuments/LogExpert
> 
> I worked around it by creating an `Own directory` for persistence file location under `AppData\Local`

That's strange, AppData\Local\ is the standard save location, if you don't configure anything

**Comment by Hirogen** [comment]
Please check with the Release 1.8.8 if this is working again (should be release pretty soonish)

**Comment by RandallFlagg** [comment]
@Hirogen is this still an issue in the .net8 release?
If not, can it be closed?

**Comment by Hirogen** [comment]
no should not be, I'll close it
