### ISSUE TITLE
Openning error: Index out of range

### ISSUE THREAD

**Issue by Pr0metheus2** [LogExperts/LogExpert#141]
Hello,
the following error occured during random consecutive LogExpert start:

![image](https://user-images.githubusercontent.com/9161285/67361455-fbb72b00-f568-11e9-8edc-cdd30b835671.png)

After windows 10 restart, the application works again. However, I cannot reproduce this error.

Logexpert version 1.8.2, 1.7.1.
Windows 10 x64

Regards.

**Comment by zarunbal** [comment]
You could maybe look in the log folder and post the log file with the error (more [infos](https://github.com/zarunbal/LogExpert/wiki/FAQ#logging))

**Comment by DR5Guy** [comment]
The error happens when the following mutex cannot be created:

`Mutex mutex = new System.Threading.Mutex(false, "Local\\LogExpertInstanceMutex" + pId, out isCreated);`

In my case this happened after the app crashed. I guess restating Windows helps reset the mutex.

**Comment by DR5Guy** [comment]
I am wondering if the following change makes sense:

`Mutex mutex = new System.Threading.Mutex(false, "Local\\LogExpertInstanceMutex" + pId, out isCreated);
try 
{
...
}
finally 
{
 mutex.Close();
}
`

Currently, any exception that happens between new mutex and mutex.close will cause the mutex to remain open and the next run is likely to fail.

**Comment by LievenDeFoor** [comment]
Got here after having receiving the same error. Will try rebooting...

**Comment by chriseggroll** [comment]
I was having this issue and checked task manager, saw an instance of logexpert running but had no files open.  killing this task allowed me to open files afterwards.

**Comment by chriseggroll** [comment]
Ok, I found this thread:  https://forums.mirthproject.io/forum/mirth-connect/support/16092-problem-with-mirth-connect-font-size

Changing the DPI scaling on launcher.exe for the administrator launcher seemed to do the trick.  I'll try it a few times before closing this bug.

**Comment by Hirogen** [comment]
> Ok, I found this thread:  https://forums.mirthproject.io/forum/mirth-connect/support/16092-problem-with-mirth-connect-font-size
> 
> 
> 
> Changing the DPI scaling on launcher.exe for the administrator launcher seemed to do the trick.  I'll try it a few times before closing this bug.

I don't see what the link has to do with this issue?

**Comment by chriseggroll** [comment]
My mistake, not sure how I posted here

**Comment by nitin065** [comment]
I am facing the same issue. I will try to restart but is there any other workaround?

**Comment by nitin065** [comment]
I do. Here is what I extracted from logexpert.log. Let me know any other log is needed.

```
2024-06-06 08:58:03.8384|INFO|Program|
============================================================================
LogExpert 1.9.0 started.
============================================================================
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 0, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 1, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 2, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 3, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 4, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 5, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 25, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 100, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 200, file: <redacted>
2024-06-06 08:58:23.2206|ERROR|LogExpert.Classes.Log.LogfileReader|Cannot find buffer for line 400, file: <redacted>
2024-06-06 09:12:10.2224|INFO|Program|
============================================================================
LogExpert 1.9.0 started.
============================================================================
2024-06-06 09:12:10.4871|WARN|LogExpert.Classes.LogExpertProxy|first GUI thread window is disposed. Setting a new one.
2024-06-06 09:12:10.5512|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)
2024-06-06 09:12:10.5512|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)
2024-06-06 09:12:20.4392|INFO|Program|
============================================================================
LogExpert 1.9.0 started.
============================================================================
2024-06-06 09:12:20.7072|WARN|LogExpert.Classes.LogExpertProxy|first GUI thread window is disposed. Setting a new one.
2024-06-06 09:12:20.7092|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)
2024-06-06 09:12:20.7092|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)
2024-06-06 09:12:41.0914|INFO|Program|
============================================================================
LogExpert 1.9.0 started.
============================================================================
2024-06-06 09:12:41.4324|WARN|LogExpert.Classes.LogExpertProxy|first GUI thread window is disposed. Setting a new one.
2024-06-06 09:12:41.4354|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)
2024-06-06 09:12:41.4354|ERROR|Program|Mutex error, giving up: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index System.ArgumentOutOfRangeException System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Server stack trace: 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at LogExpert.Classes.LogExpertProxy.LoadFiles(String[] fileNames)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LogExpert.Classes.LogExpertProxy.NewWindowOrLockedWindow(String[] fileNames)
   at LogExpert.Program.Sub_Main(String[] orgArgs)

```

**Comment by RandallFlagg** [comment]
@Hirogen  is this issue solved in the .net 8 version? If yes, can it be closed?

**Comment by RandallFlagg** [comment]
@odinian Did you try the new version? Please post the stacktrace if it happens in it. The code path shown here is not relevant in the new version.

**Comment by odinian** [comment]
@RandallFlagg , sorry, I'm using the version available on Chocolatey, and it's 1.9.0. I posted there about the new version, so hopefully someone there will update the package.

**Comment by Hirogen** [comment]
> [@RandallFlagg](https://github.com/RandallFlagg) , sorry, I'm using the version available on Chocolatey, and it's 1.9.0. I posted there about the new version, so hopefully someone there will update the package.

I'll update the package in the evening

**Comment by odinian** [comment]
> > [@RandallFlagg](https://github.com/RandallFlagg) , sorry, I'm using the version available on Chocolatey, and it's 1.9.0. I posted there about the new version, so hopefully someone there will update the package.
> 
> I'll update the package in the evening

Thanks! I’ll keep my on the chocolatey package.

**Comment by Hirogen** [comment]
latest version is pushed to choco and awaits moderation => https://community.chocolatey.org/packages/logexpert

**Comment by odinian** [comment]
I'm no longer seeing the errors. thanks.
