### ISSUE TITLE
Open an lxj get the below error

### ISSUE THREAD

**Issue by voltz5000** [LogExperts/LogExpert#176]
Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content.

InvalidOperationException
   at WeifenLuo.WinFormsUI.Docking.DockPane.set_ActiveContent(IDockContent value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Activate()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetParent(Control value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetPane(DockPane pane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockPanel.Persistor.LoadFromXml(DockPanel dockPanel, Stream stream, DeserializeDockContent deserializeContent, Boolean closeStream)
   at LogExpert.LogTabWindow.RestoreLayout(String layoutXml)
   at LogExpert.LogTabWindow.LoadProject(String projectFileName, Boolean restoreLayout)
   at LogExpert.LogTabWindow.LogTabWindow_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Hirogen** [comment]
Could you elaborate what you did, and how it happend, also what version did you use? Please test it with version 1.8.7 again.

**Comment by RandallFlagg** [comment]
@Hirogen I think this can be closed as the stack is not relevant with the .net 8 version and no other information was received from @voltz5000
