### ISSUE TITLE
OutOfMemoryException TimeSpreadCalculator

### ISSUE THREAD

**Issue by Hirogen** [LogExperts/LogExpert#250]
# Bug
Array dimensions exceeded supported range.
OutOfMemoryException
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at LogExpert.Classes.TimeSpreadCalculator.DoCalc() in D:\Hiro\GitHub\LogExpert\src\LogExpert\Classes\TimeSpreadCalculator.cs:line 255
   at LogExpert.Classes.TimeSpreadCalculator.WorkerFx() in D:\Hiro\GitHub\LogExpert\src\LogExpert\Classes\TimeSpreadCalculator.cs:line 198
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Important questions
- LogExpert Version: 1.9.0 - HIGH DPI
- Windows Version: 10
- Local file or Network: Local file
- Used Columnizer: standard
- Is this version specific or a new problem: since 1.9.0

file is open in the background, logexperts runs in the background and starts throwing this exception

**Comment by RandallFlagg** [comment]
@Hirogen can you write steps to reproduce? There is a big chance that this is solved in the .net 8 version.

**Comment by Hirogen** [comment]
I'll take a look, but you are probably right
