### ISSUE TITLE
Getting an exception whenever i'm copying a line

### ISSUE THREAD

**Issue by Noctis-** [LogExperts/LogExpert#259]
# Bug
Selecting a line and copying it throws an exception.
Interesting. This happened twice today, but after restarting it, it seems to be acting up ok . I wonder if it only happens once the log is "live" and then you copy an item ... i'll retest this a bit later after my log file has been live

Important questions
- LogExpert Version:  1.9.0
- Windows Version: Win 10 - 21H2 
- Local file 
- Used Columnizer - default
- Is this version specific or a new problem: Cant tell, having 1.9 installed

Optional questions(depends on the problem):
- Continous appending log file? -> Yes
- Size of the file -> 60Kb
- some specific settings  -> nope
- Screenshot -> 

Here is the exception text : 

```
Requested Clipboard operation did not succeed.

ExternalException
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at LogExpert.Controls.LogWindow.LogWindow.CopyMarkedLinesToClipboard()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Hirogen** [comment]
please check with the new version https://github.com/LogExperts/LogExpert/releases/tag/v.1.12.0
